### ISSUE TITLE
Unsupported operand type error report.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/custom_header_block#3]
I get the error message
`Error: Unsupported operand types in custom_header_block_header_block() (line 28 of ...../modules/custom_header_block/custom_header_block.module).`

**Comment by jjmonterey** [comment]
I got the same error. The problem I think is a typo in line 27:   $settings += array( 
I deleted the + to read:  $settings = array(  and the error disappeared .

**Comment by docwilmot** [comment]
Thanks for reporting. Seems there were changes to API functions in https://github.com/backdrop/backdrop-issues/issues/2713 that caused this: the `$settings` parameter was removed from `hook_block_view_MODULE_DELTA_alter()` then, so instead its now NULL instead of array. WIll try and fix later.

**Comment by argiepiano** [comment]
@docwilmot, @jjmonterey I was on a plane today with not much to do and looked into this 😄 I provided a PR that has fixed this issue in my testing. Please test, and possibly consider merging. 

PR #4

**Comment by jjmonterey** [comment]
@argiepiano, @docwilmot  Thanks for responding. My lack of PHP expertise is telling, but at least I can report errors.
